### ISSUE TITLE
FE Allows Double Claiming Withdrawals Attempts

### ISSUE THREAD

**Issue by shahar4** [matter-labs/dapp-portal#205] opened 2024-12-17 11:00 UTC
**Conetxt**
There is a FE-only bug: The portal incorrectly lets users double-claim a withdrawal. When they do, a misleading error message appears. See [this issue](https://github.com/zkSync-Community-Hub/zksync-developers/discussions/831) for more details on the error.

**Acceptance Criteria**
- Immediate: 
  - Claiming a withdrawal for the second time is disabled.
- Follow-ups:
  - Once a withdrawal has been claimed, it is clear to the user the funds have been transferred.
  - All relevant user-facing error messages are reworded to provide context to the user

**Comment by bogatyy** [comment] 2024-12-19 17:15
To add a bit more context:
* portal allows trying to finalize an already finalized withdrawal, that's the biggest problem
* when this attempt invariably fails, the error message is misleading. `BatchNotExecuted` = too early to finalize; should instead be `WithdrawalAlreadyFinalized` https://github.com/matter-labs/era-contracts/blob/46d75088e7ddb534101874c3ec15b877da1cb417/l1-contracts/contracts/common/L1ContractErrors.sol#L294

**Comment by popzxc** [comment] 2024-12-20 07:02
@bogatyy regarding the error message: if error message shows the signature of `BatchNotExecuted`, it means that the contract _indeed_ returned this error, so it's not that front-end decides to report wrong contract event. It means that it was [really emitted](https://github.com/matter-labs/era-contracts/blob/dev/l1-contracts/contracts/state-transition/chain-deps/facets/Mailbox.sol#L121). AFAIU `WithdrawalAlreadyFinalized` is only emitted for legacy bridge. This is something to be discussed with the protocol team.

---

That said, I've dug a bit into this issue and the most sus part so far is this line:
https://github.com/matter-labs/dapp-portal/blob/main/store/zksync/withdrawals.ts#L41

Basically, if checking if withdrawal is finalized fails due to an exception, we silently assume that withdrawal is not finalized. Additionally, it always assumes that index of withdrawal is 0, which probably won't work with transactions that made several withdrawals with a single tx, but it feels less important right now.

Regarding error message formatting -- I guess we can for now [adapt formatters](https://github.com/matter-labs/dapp-portal/blob/main/utils/formatters.ts#L132) to add `reverted with the following signature: 0x2078a6a0` to the list of checked strings. The reason why it cannot decode the signature is because SDK doesn't know about new contracts, so for that to be fixed SDK has to be updated first (which is a separate and bigger issue).

**Comment by tx-nikola** [comment] 2024-12-23 12:46
@popzxc can we close this issue?

**Comment by popzxc** [comment] 2024-12-25 03:24
It was discovered that the issue is already fixed.

**Closed by popzxc** 2024-12-25 03:24 UTC
